---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "openclaw.fullname" . | quote }}
  {{- with (merge .Values.global.labels .Values.service.labels (include "openclaw.labels" . | fromYaml)) }}
  labels:
    {{- range $k, $v := . }}
    {{- $v = tpl $v $ }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
  {{- with (merge .Values.global.annotations .Values.service.annotations) }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ | quote }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector: {{- include "openclaw.selectorLabels" . | nindent 4 }}
  sessionAffinity: {{ .Values.service.sessionAffinity | quote }}
  ports:
    - name: "http"
      port: {{ .Values.openclaw.ports.http }}
      targetPort: "http"
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
