name: openclaw
description: A Helm chart for OpenClaw
home: https://github.com/openclaw/openclaw
sources:
  - https://github.com/openclaw/openclaw
appVersion: "v2026.9.1"

apiVersion: v2
type: application
version: "0.2.3"

maintainers:
  - name: jacobeatsspam
    url: https://github.com/jacobeatsspam
